### ISSUE TITLE
Compilation error with Solidity >= 0.8.1

### ISSUE THREAD

**Issue by ItsNickBarry** [mudgen/diamond-2#3]
I am attempting to adapt this implementation for use in [@solidstate/contracts](https://github.com/solidstate-network/solidstate-contracts).  The  library is designed to work with Solidity versions `0.8.x`, but the diamond contracts do not compile with versions `0.8.1` and above.  This error is returned: 

`CompilerError: Stack too deep when compiling inline assembly: Variable dataEnd is 1 slot(s) too deep inside the stack.`

Any idea what this means or where it's coming from?  An plans to upgrade this repository for compatibility with `0.8.x`?

**Comment by mudgen** [comment]
Yes, this is a bug in the Solidity optimizer which I reported here: https://github.com/ethereum/solidity/issues/10930

The Aavegotchi Diamond uses Solidity 0.8.1.  I solved this problem by deploying a minimal diamond and then executing an upgrade immediately after: https://github.com/aavegotchi/aavegotchi-contracts/blob/master/contracts/shared/Diamond.sol

Don't know when/if this repository will be updated/changed.  I'm really busy with Aavegotchi.  It depends if someone makes a pull request to change it.

**Comment by ItsNickBarry** [comment]
I was able to get it to compile by removing the `DiamondArgs` struct and assigning ownership to `msg.sender` rather than to a passed address.  Closing because Solidity will probably be fixed eventually, and `0.8.x` support isn't strictly necessary for a reference implementation.
